# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nfl_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pick',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
