# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_auto_20171112_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nfl_id',
            field=models.IntegerField(unique=True),
        ),
    ]
