# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0005_auto_20171112_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='P', max_length=3),
            preserve_default=False,
        ),
    ]
