# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0006_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(max_length=4),
        ),
    ]
