# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0007_auto_20171211_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='pretty_year',
            field=models.CharField(default=112.05555555555556, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pick',
            name='choice',
            field=models.IntegerField(default=3),
        ),
    ]
